services:
  postgresql:
      container_name: postgresql
      image: postgres:16
      environment:
        POSTGRES_USER: fusionpbx
        POSTGRES_PASSWORD: mysupersecret
        POSTGRES_DB: fusionpbx 
      restart: unless-stopped 
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U fusionpbx -d fusionpbx'"]
        interval: 10s
        timeout: 10s
        retries: 10
      ports:
        - "5432:5432"
      volumes:
        - ./volumes/postgresql/data:/var/lib/postgresql/data
        - ./volumes/postgresql/db-init/:/docker-entrypoint-initdb.d/

  fusionpbx:
    depends_on:
      - postgresql:
          condition: service_healthy
    container_name: fusionpbx
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host" 
    volumes:
      - "./volumes/fusion/switch.conf:/etc/freeswitch"
      - "./volumes/fusion/switch.sounds:/usr/share/freeswitch/sounds"
      - "./volumes/fusion/switch.database:/var/lib/freeswitch/db"
      - "./volumes/fusion/switch.recordings:/var/lib/freeswitch/recordings"
      - "./volumes/fusion/switch.storage:/var/lib/freeswitch/storage"
      - "./volumes/fusion/switch.voicemail:/var/lib/freeswitch/storage/voicemail"
      - "./volumes/fusion/switch.scripts:/usr/share/freeswitch/scripts"
    environment:
      X_PG_USER: fusionpbx
      X_PG_HOST: localhost
      X_PG_PORT: 5432
      X_PG_PASSWORD: mysupersecret
    restart: unless-stopped
    privileged: true
    tty: true
