services:
  postgresql:
      image: postgres:16
      environment:
        POSTGRES_USER: fusionpbx
        POSTGRES_PASSWORD: mysupersecret
        POSTGRES_DB: fusionpbx 
      restart: unless-stopped 
      ports:
        - "5432:5432"
      volumes:
        - ./volumes/postgresql/data:/var/lib/postgresql/data
        - ./volumes/postgresql/db-init/:/docker-entrypoint-initdb.d/

  fusion:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host" 
    volumes:
      - ./entrypoint.example.sh:/usr/src/fusionpbx-install.sh/entrypoint.sh
    #   - "./volumes/fusion/switch.conf:/etc/freeswitch"
    #   - "./volumes/fusion/switch.sounds:/usr/share/freeswitch/sounds"
    #   - "./volumes/fusion/switch.database:/var/lib/freeswitch/db"
    #   - "./volumes/fusion/switch.recordings:/var/lib/freeswitch/recordings"
    #   - "./volumes/fusion/switch.storage:/var/lib/freeswitch/storage"
    #   - "./volumes/fusion/switch.voicemail:/var/lib/freeswitch/storage/voicemail"
    #   - "./volumes/fusion/switch.scripts:/usr/share/freeswitch/scripts"
    environment:
      X_PG_USER: fusionpbx
      X_PG_HOST: localhost
      X_PG_PORT: 5432
      X_PG_PASSWORD: mysupersecret
    restart: unless-stopped
    privileged: true
    tty: true
